// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACG41vBwSqPt6vSyzFz_oAyqqcwxHJA88',
    appId: '1:598499004389:web:0dbec4482e7a4ed1f5690c',
    messagingSenderId: '598499004389',
    projectId: 'winners2-5055a',
    authDomain: 'winners2-5055a.firebaseapp.com',
    storageBucket: 'winners2-5055a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdf4sch-jHZEF50KWAGQQYzil2iU4TmRc',
    appId: '1:598499004389:android:eaa30905c0904bd1f5690c',
    messagingSenderId: '598499004389',
    projectId: 'winners2-5055a',
    storageBucket: 'winners2-5055a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCky6X-Z9-83AFvxqtwWndm9Wk3TPbjwzc',
    appId: '1:598499004389:ios:e07cb7111a0e334af5690c',
    messagingSenderId: '598499004389',
    projectId: 'winners2-5055a',
    storageBucket: 'winners2-5055a.appspot.com',
    iosClientId: '598499004389-2rkkv590j65i4rnveha4jh6bnb9pir4l.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWeekend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCky6X-Z9-83AFvxqtwWndm9Wk3TPbjwzc',
    appId: '1:598499004389:ios:e07cb7111a0e334af5690c',
    messagingSenderId: '598499004389',
    projectId: 'winners2-5055a',
    storageBucket: 'winners2-5055a.appspot.com',
    iosClientId: '598499004389-2rkkv590j65i4rnveha4jh6bnb9pir4l.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWeekend',
  );
}
